config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :members

  resources :meeting_members

  resources :belts

  resources :roles

  resources :schools

  resources :meetings

  get 'test', controller: :meetings, action: :test, as: :test

  resources :meeting_types

  # You can have the root of your site routed with "root"
  root 'home#index'

  get 'home/reports' => 'home#reports', as: :reports
  
  get 'home/poor_attendance' => 'home#poor_attendance', as: :poor_attendance
  get 'home/slacker_report' => 'home#slacker_report', as: :slacker_report
  get 'home/classes_per_student' => 'home#classes_per_student', as: :classes_per_student
  get 'home/people_per_class' => 'home#people_per_class', as: :people_per_class

  get 'attendance/(for/:school)', controller: :meetings, action: :new, as: :attendance

  get 'dashboard/(for/:school)', controller: :home, action: :dashboard, as: :dashboard

  get 'home/attendance', controller: :home, action: :attendance_for_all_time
  get 'home/attendance/:year', controller: :home, action: :attendance_for_year
  get 'home/attendance/:year/:month', controller: :home, action: :attendance_for_month
end

app/models/meeting_member.rb
class MeetingMember < ApplicationRecord
  belongs_to :member
  belongs_to :meeting
  belongs_to :belt
  belongs_to :role

  scope :met_after, ->(time) { joins(:meeting).merge(Meeting.met_after(time)) }
  scope :met_between, ->(start_time, end_time) { joins(:meeting).merge(Meeting.met_between(start_time, end_time)) }
  scope :meetings_for_member, ->(member) { where("member_id = ?", member.id) }

  def to_keen_props
    {
      meeting: {
        id: meeting.id,
        pretty_name: meeting.pretty_name,
        day_of_week: meeting.met.strftime('%a'),
        meeting_type: {
          name: meeting.meeting_type.name,
          id: meeting.meeting_type.id
        },
        school: {
          id: meeting.school.id,
          name: meeting.school.name
        }
      },
      member: {
        id: member.id,
        first_name: member.first_name,
        last_name: member.last_name,
        current_belt: {
          id: member.belt.id,
          name: member.belt.name
        }
      },
      keen: {
        timestamp: meeting.met.iso8601
      }
    }
  end
end

app/controllers/meeting_members_controller.rb
class MeetingMembersController < ApplicationController
  before_action :set_meeting_member, only: [:show, :edit, :update, :destroy]

  # GET /meeting_members
  # GET /meeting_members.json
  def index
    @meeting_members = MeetingMember.all
  end

  def for_member
    meeting_members = MeetingMember.meetings_for_member(params[:member_id]).include(:meeting)
    @meetings = meeting_members.collect { |mm| mm.meeting }

    respond_to do |format|
      format.json { render json: @meetings.to_json(include: :meeting_type) }
    end
  end

  # GET /meeting_members/1
  # GET /meeting_members/1.json
  def show
  end

  # GET /meeting_members/new
  def new
    @meeting_member = MeetingMember.new
  end

  # GET /meeting_members/1/edit
  def edit
  end

  # POST /meeting_members
  # POST /meeting_members.json
  def create
    meeting = Meeting.new({
      meeting_type: MeetingType.find(meeting_member_params[:meeting_type]),
      met: meeting_member_params[:date]
    })

    meeting.save
    memberIds = meeting_member_params[:members]

    memberIds.each do |memId|
      member = Member.find(memId)

      if member
        mm = MeetingMember.new({
          meeting: meeting,
          member: member,
          belt: member.belt,
        })

        mm.save
      end
    end

    @meeting_member = MeetingMember.new(meeting_member_params)

    respond_to do |format|
      if @meeting_member.save
        format.html { redirect_to @meeting_member, notice: 'Meeting member was successfully created.' }
        format.json { render :show, status: :created, location: @meeting_member }
      else
        format.html { render :new }
        format.json { render json: @meeting_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meeting_members/1
  # PATCH/PUT /meeting_members/1.json
  def update
    respond_to do |format|
      if @meeting_member.update(meeting_member_params)
        format.html { redirect_to @meeting_member, notice: 'Meeting member was successfully updated.' }
        format.json { render :show, status: :ok, location: @meeting_member }
      else
        format.html { render :edit }
        format.json { render json: @meeting_member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meeting_members/1
  # DELETE /meeting_members/1.json
  def destroy
    @meeting_member.destroy
    respond_to do |format|
      format.html { redirect_to meeting_members_url, notice: 'Meeting member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meeting_member
      @meeting_member = MeetingMember.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meeting_member_params
      params.require(:meeting_member).permit(:meeting_type, :date, :instructor, :members)
    end
end

app/helpers/meeting_members_helper.rb
module MeetingMembersHelper
end

app/views/meeting_members/edit.html.haml
- model_class = MeetingMember
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/meeting_members/index.html.haml
- model_class = MeetingMember
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:meeting_id)
      %th= model_class.human_attribute_name(:member_id)
      %th= model_class.human_attribute_name(:role_id)
      %th= model_class.human_attribute_name(:belt_id)
      %th= model_class.human_attribute_name(:created_at)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @meeting_members.each do |meeting_member|
      %tr
        %td= link_to meeting_member.id, meeting_member_path(meeting_member)
        %td= meeting_member.meeting_id
        %td= meeting_member.member_id
        %td= meeting_member.role_id
        %td= meeting_member.belt_id
        %td= l meeting_member.created_at
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_meeting_member_path(meeting_member), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), meeting_member_path(meeting_member), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger' 
= link_to t('.new', :default => t("helpers.links.new")), new_meeting_member_path, :class => 'btn btn-primary'

app/views/meeting_members/new.html.haml
- model_class = MeetingMember
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize

  #carousel.carousel.slide{:data => {:ride => "carousel"}}
    .carousel-inner{:role => "listbox"}
      .item.active
        #meeting-type-select-container
          %h3 1. Choose a Meeting Type and Time:
          .input-group
            %select#meeting-type.form-control
              %option{:value => ""}
                Class Type
              - MeetingType.all.each do |type|
                %option{:value => "#{type.id}"}
                  = type.name

          .input-group
            #datetimepicker.input-append.date
              %input#meeting-date{:data => {:format => "MM/dd/yyyy hh:mm PP"}, :type => "text", :value => "#{DateTime.now().strftime("%m/%d/%Y %I:%M %P")}"}

          .input-group
            %select#instructor.form-control
              - Member.where(is_teacher: true).each do |member|
                %option{:value => "#{member.id}"}
                  = member.full_name

          %a.btn.next-btn{:href => "#", :data => {:validate => "step_one"}} Select Students &#10095;

      .item
        #members-select-container
          %h3
            2. Select Who Attended
            %span.meeting-name
          = render "members/member_select"

          %h4 Students - Click to Remove:
          #selected-members-container{:style => ""}
            None selected yet.

          %br
          %br

          %a.btn.back-btn{:href => "#", :data => {:validate => "step_two"}} &#10094; Back
          &nbsp;
          %a.btn.next-btn.confirm{:href => "#"} Confirm &#10095;

      .item
        #members-confirm-container
          %h3
            3. Confirm Attendance

          %h4 Class Info:
          #class-info.container
            %table
              %tr
                %th{:style => "text-align: right;"}
                  Class Type:
                %td#meeting-type-confirm
              %tr
                %th{:style => "text-align: right;"}
                  Date:
                %td#date-confirm
              %tr
                %th{:style => "text-align: right;"}
                  Instructor:
                %td#instructor-confirm

          %h4 Attending Students:
          #attending-students

          %br
          %br

          %a.btn.back-btn{:href => "#"} &#10094; Back
          %a#submit-btn.btn.btn-primary{:href => "#"} Submit

  .create-form
    %form
      %input{:type => "hidden", :id => "meeting_type_id", :name => "meeting_type_id"}

:javascript
$(document).ready(function() {
  $("#carousel").carousel({
    interval: false,
    wrap: false,
    keyboard: false
  });
  
  $.each($(".next-btn"), function(ndx, btn) {
    $(btn).click(function(event) {
      event.preventDefault();

      // handle validations, its heavy handed, but meh
      var vald = $(btn).data("validate");
      var isValid = true;
      var errorMsg = [];

      if (vald != undefined) {
        if (vald == "step_one") {
          if ($("#meeting-type").val() == "") {
            isValid = false;
            errorMsg.push("Must select a class type.");
          }

          if ($("#meeting-date").val() == "") {
            isValid = false;
            errorMsg.push("Must have a valid date and time.");
          }

          if ($("#instructor").val() == "") {
            isValid = false;
            errorMsg.push("Must select an instructor..");
          }
        } else if (vald == "step_two") {
        }

        if (!isValid) {
          alert(errorMsg.join(", "));
          return;
        }
      }

      if ($(btn).hasClass("confirm")) {
        var meetingType = $("#meeting-type").val();
        $("#meeting-type-confirm").html($("#meeting-type option[value=" + String(meetingType) + "]").text());

        var date = $("#meeting-date").val();
        $("#date-confirm").html(date);

        var instructor = $("#instructor").val();
        $("#instructor-confirm").html($("#instructor option[value=" + String(instructor) + "]").text());

        var memberIds = [];
        $.each(mem.list(), function(ndx, item) {
          $("#attending-students").append("<span style=\"margin-right: 5px;\">" + item.value + "</span>");
          memberIds.push(item.id);
        });

        $("#submit-btn").click(function(event) {
          $.ajax({
            url: "#{meeting_members_path()}",
            method: "post",
            data: {
              meeting_type: meetingType,
              date: date,
              instructor: instructor,
              members: memberIds
            }
          }).done(function(json) {
            alert("Yay, you submitted and stuff.");
          });
        });
      }

      $("#carousel").carousel('next');
    });
  });
  
  $.each($(".back-btn"), function(ndx, btn) {
    $(btn).click(function(event) {
      event.preventDefault();
      $("#carousel").carousel('prev');
    });
  });

  var elem = $("#selected-members-container");
  var mem = new Members(elem);

  $("#find-student .typeahead").on('typeahead:selected', function(evt, item) {
    mem.addMember(item);

    $("#find-student span input.tt-input").val("");
    $("#find-student span input.tt-input").focus();
  });
});

app/views/meeting_members/show.html.haml
- model_class = MeetingMember
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:meeting_id)
      \:
  %dd= @meeting_member.meeting_id
  %dt
    %strong
      = model_class.human_attribute_name(:member_id)
      \:
  %dd= @meeting_member.member_id
  %dt
    %strong
      = model_class.human_attribute_name(:role_id)
      \:
  %dd= @meeting_member.role_id
  %dt
    %strong
      = model_class.human_attribute_name(:belt_id)
      \:
  %dd= @meeting_member.belt_id
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), meeting_members_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_meeting_member_path(@meeting_member), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), meeting_member_path(@meeting_member), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'