config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :members

  resources :meeting_members

  resources :belts

  resources :roles

  resources :schools

  resources :meetings

  get 'test', controller: :meetings, action: :test, as: :test

  resources :meeting_types

  # You can have the root of your site routed with "root"
  root 'home#index'

  get 'home/reports' => 'home#reports', as: :reports
  
  get 'home/poor_attendance' => 'home#poor_attendance', as: :poor_attendance
  get 'home/slacker_report' => 'home#slacker_report', as: :slacker_report
  get 'home/classes_per_student' => 'home#classes_per_student', as: :classes_per_student
  get 'home/people_per_class' => 'home#people_per_class', as: :people_per_class

  get 'attendance/(for/:school)', controller: :meetings, action: :new, as: :attendance

  get 'dashboard/(for/:school)', controller: :home, action: :dashboard, as: :dashboard

  get 'home/attendance', controller: :home, action: :attendance_for_all_time
  get 'home/attendance/:year', controller: :home, action: :attendance_for_year
  get 'home/attendance/:year/:month', controller: :home, action: :attendance_for_month
end

app/models/school.rb
class School < ApplicationRecord
end

app/controllers/schools_controller.rb
class SchoolsController < ApplicationController
  skip_before_action :check_school
  before_action :set_school, only: [:show, :edit, :update, :destroy]

  # GET /schools
  # GET /schools.json
  def index
    @schools = School.all
  end

  # GET /schools/1
  # GET /schools/1.json
  def show
  end

  # GET /schools/new
  def new
    @school = School.new
  end

  # GET /schools/1/edit
  def edit
  end

  # POST /schools
  # POST /schools.json
  def create
    @school = School.new(school_params)

    respond_to do |format|
      if @school.save
        format.html { redirect_to @school, notice: 'School was successfully created.' }
        format.json { render :show, status: :created, location: @school }
      else
        format.html { render :new }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /schools/1
  # PATCH/PUT /schools/1.json
  def update
    respond_to do |format|
      if @school.update(school_params)
        format.html { redirect_to @school, notice: 'School was successfully updated.' }
        format.json { render :show, status: :ok, location: @school }
      else
        format.html { render :edit }
        format.json { render json: @school.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schools/1
  # DELETE /schools/1.json
  def destroy
    @school.destroy
    respond_to do |format|
      format.html { redirect_to schools_url, notice: 'School was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_school
      @school = School.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def school_params
      params.require(:school).permit(:name, :slug, :comment, :is_active)
    end
end

app/helpers/schools_helper.rb
module SchoolsHelper
end

app/views/schools/_form.html.haml
= form_for @school, :html => { :class => 'form-horizontal' } do |f|
  .control-group
    = f.label :name, :class => 'control-label'
    .controls
      = f.text_field :name, :class => 'text_field'
  .control-group
    = f.label :slug, :class => 'control-label'
    .controls
      = f.text_field :slug, :class => 'text_field'
  .control-group
    = f.label :comment, :class => 'control-label'
    .controls
      = f.text_field :comment, :class => 'text_field'
  .control-group
    = f.label :is_active, :class => 'control-label'
    .controls
      = f.check_box :is_active, :class => 'check_box'
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), schools_path, :class => 'btn'

app/views/schools/edit.html.haml
- model_class = School
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/schools/index.html.haml
- model_class = School
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:id)
      %th= model_class.human_attribute_name(:name)
      %th= model_class.human_attribute_name(:slug)
      %th= model_class.human_attribute_name(:comment)
      %th= model_class.human_attribute_name(:is_active)
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @schools.each do |school|
      %tr
        %td= link_to school.id, school_path(school)
        %td= school.name
        %td= school.slug
        %td= school.comment
        %td= school.is_active
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_school_path(school), :class => 'btn btn-mini'
          = link_to t('.destroy', :default => t("helpers.links.destroy")), school_path(school), :method => :delete, :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-mini btn-danger'
= link_to t('.new', :default => t("helpers.links.new")), new_school_path, :class => 'btn btn-primary'

app/views/schools/new.html.haml
- model_class = School
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/schools/show.html.haml
- model_class = School
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize
%dl.dl-horizontal
  %dt
    %strong
      = model_class.human_attribute_name(:name)
      \:
  %dd= @school.name
  %dt
    %strong
      = model_class.human_attribute_name(:slug)
      \:
  %dd= @school.slug
  %dt
    %strong
      = model_class.human_attribute_name(:comment)
      \:
  %dd= @school.comment
  %dt
    %strong
      = model_class.human_attribute_name(:is_active)
      \:
  %dd= @school.is_active
.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), schools_path, :class => 'btn'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_school_path(@school), :class => 'btn'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), school_path(@school), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'