config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :members

  resources :meeting_members

  resources :belts

  resources :roles

  resources :schools

  resources :meetings

  get 'test', controller: :meetings, action: :test, as: :test

  resources :meeting_types

  # You can have the root of your site routed with "root"
  root 'home#index'

  get 'home/reports' => 'home#reports', as: :reports
  
  get 'home/poor_attendance' => 'home#poor_attendance', as: :poor_attendance
  get 'home/slacker_report' => 'home#slacker_report', as: :slacker_report
  get 'home/classes_per_student' => 'home#classes_per_student', as: :classes_per_student
  get 'home/people_per_class' => 'home#people_per_class', as: :people_per_class

  get 'attendance/(for/:school)', controller: :meetings, action: :new, as: :attendance

  get 'dashboard/(for/:school)', controller: :home, action: :dashboard, as: :dashboard

  get 'home/attendance', controller: :home, action: :attendance_for_all_time
  get 'home/attendance/:year', controller: :home, action: :attendance_for_year
  get 'home/attendance/:year/:month', controller: :home, action: :attendance_for_month
end

app/views/layouts/application.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Quantum Attendance"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application", 'data-turbolinks-track': 'reload'
    = javascript_include_tag "handlebars"
    = stylesheet_link_tag "//d26b395fwzu5fz.cloudfront.net/keen-dataviz-1.1.0.css"
    = javascript_include_tag "//d26b395fwzu5fz.cloudfront.net/keen-dataviz-1.1.0.js"
    = javascript_include_tag "//d26b395fwzu5fz.cloudfront.net/keen-analysis-1.2.0.js"
    :javascript
      //!function(a,b){a("Keen","https://d26b395fwzu5fz.cloudfront.net/3.4.1/keen.min.js",b)}(function(a,b,c){var d,e,f;c["_"+a]={},c[a]=function(b){c["_"+a].clients=c["_"+a].clients||{},c["_"+a].clients[b.projectId]=this,this._config=b},c[a].ready=function(b){c["_"+a].ready=c["_"+a].ready||[],c["_"+a].ready.push(b)},d=["addEvent","setGlobalProperties","trackExternalLink","on"];for(var g=0;g<d.length;g++){var h=d[g],i=function(a){return function(){return this["_"+a]=this["_"+a]||[],this["_"+a].push(arguments),this}};c[a].prototype[h]=i(h)}e=document.createElement("script"),e.async=!0,e.src=b,f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(e,f)},this);
  %body{"style" => "margin-top: 45px"}
    = nav_bar fixed: :top, brand: "Quantum", responsive: true do
      = menu_group do
        = menu_item "Classes", meetings_path
        = menu_divider
        = menu_item "Members", members_path
        = menu_divider
        = drop_down "Reports" do
          = menu_item "Slacker Report", slacker_report_path
          = menu_item "Poor Attendance", poor_attendance_path
          = menu_item "Classes Per Student", classes_per_student_path
          = menu_item "People Per Class", people_per_class_path

      .navbar-form.navbar-right
        .form-group
          = select_tag :school_select, options_for_select(School.all.collect{|school| [school.name, school.slug]}.insert(0, ['All Schools', 'none']), @_current_school ? @_current_school.slug : nil), class: "form-control"

    .container-fluid
      .row
        .col-md-1
        .col-md-10
          .row
            = bootstrap_flash
            = yield
          .row{"style" => "padding-top: 10px;"}
            %footer
              %p © Quantum Martial Arts 2017
        .col-md-1
    / /container

:javascript
  $(document).ready(function() {
    $("#school_select").change(function() {
      var url = window.location.href;
      var schoolVal = $("#school_select").val();

      if (url.match(/school=/)) {
        url = replaceUrlParam(url, "school", schoolVal);
      }
      else {
        url += (url.match(/\?/) ? '&' : '?') + "school=" + $("#school_select").val();
      }
      
      window.location = url;
    });
  });

  function replaceUrlParam(url, paramName, paramValue) {
    var pattern = new RegExp('\\b('+paramName+'=).*?(&|$)');

    if(url.search(pattern)>=0){
      return url.replace(pattern,'$1' + paramValue + '$2');
    }

    return url + (url.indexOf('?')>0 ? '&' : '?') + paramName + '=' + paramValue 
  }

app/views/layouts/mobile.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Quantum Attendance"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"
    = javascript_include_tag "handlebars"
    = stylesheet_link_tag "//d26b395fwzu5fz.cloudfront.net/keen-dataviz-1.1.0.css"
    = javascript_include_tag "//d26b395fwzu5fz.cloudfront.net/keen-dataviz-1.1.0.js"
    = javascript_include_tag "//d26b395fwzu5fz.cloudfront.net/keen-analysis-1.2.0.js"
    :javascript
      //!function(a,b){a("Keen","https://d26b395fwzu5fz.cloudfront.net/3.4.1/keen.min.js",b)}(function(a,b,c){var d,e,f;c["_"+a]={},c[a]=function(b){c["_"+a].clients=c["_"+a].clients||{},c["_"+a].clients[b.projectId]=this,this._config=b},c[a].ready=function(b){c["_"+a].ready=c["_"+a].ready||[],c["_"+a].ready.push(b)},d=["addEvent","setGlobalProperties","trackExternalLink","on"];for(var g=0;g<d.length;g++){var h=d[g],i=function(a){return function(){return this["_"+a]=this["_"+a]||[],this["_"+a].push(arguments),this}};c[a].prototype[h]=i(h)}e=document.createElement("script"),e.async=!0,e.src=b,f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(e,f)},this);
  %body
    .navbar.navbar-default
      .container-fluid
        .navbar-header
          %a.btn.btn-navbar{"data-target" => ".nav-collapse", "data-toggle" => "collapse"}
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          %a.brand{:href => "#"} Quantum
        .collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li Classes
            %li Members
            %li Reports
        / /.nav-collapse
    .container-fluid
      = bootstrap_flash
      = yield
      %footer
        %p © Quantum Martial Arts 2017
    / /container

:javascript
  $(document).ready(function() {
    $("#school_select").change(function() {
      var url = window.location.href;
      var schoolVal = $("#school_select").val();

      if (url.match(/school=/)) {
        url = replaceUrlParam(url, "school", schoolVal);
      }
      else {
        url += (url.match(/\?/) ? '&' : '?') + "school=" + $("#school_select").val();
      }
      
      window.location = url;
    });
  });

  function replaceUrlParam(url, paramName, paramValue) {
    var pattern = new RegExp('\\b('+paramName+'=).*?(&|$)');

    if(url.search(pattern)>=0){
      return url.replace(pattern,'$1' + paramValue + '$2');
    }

    return url + (url.indexOf('?')>0 ? '&' : '?') + paramName + '=' + paramValue 
  }

app/views/layouts/react.html.haml
!!!
%html{:lang => "en"}
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=Edge,chrome=1", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0", :name => "viewport"}/
    %title= content_for?(:title) ? yield(:title) : "Quantum Attendance"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    = stylesheet_link_tag "application", :media => "all"
    / For all other devices
    / Size should be 32 x 32 pixels
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application", 'data-turbolinks-track': 'reload'
    = stylesheet_link_tag "//d26b395fwzu5fz.cloudfront.net/keen-dataviz-1.1.0.css"
    = javascript_include_tag "//d26b395fwzu5fz.cloudfront.net/keen-dataviz-1.1.0.js"
    = javascript_include_tag "//d26b395fwzu5fz.cloudfront.net/keen-analysis-1.2.0.js"
    = javascript_pack_tag 'webpack-bundle'
    :javascript
      //!function(a,b){a("Keen","https://d26b395fwzu5fz.cloudfront.net/3.4.1/keen.min.js",b)}(function(a,b,c){var d,e,f;c["_"+a]={},c[a]=function(b){c["_"+a].clients=c["_"+a].clients||{},c["_"+a].clients[b.projectId]=this,this._config=b},c[a].ready=function(b){c["_"+a].ready=c["_"+a].ready||[],c["_"+a].ready.push(b)},d=["addEvent","setGlobalProperties","trackExternalLink","on"];for(var g=0;g<d.length;g++){var h=d[g],i=function(a){return function(){return this["_"+a]=this["_"+a]||[],this["_"+a].push(arguments),this}};c[a].prototype[h]=i(h)}e=document.createElement("script"),e.async=!0,e.src=b,f=document.getElementsByTagName("script")[0],f.parentNode.insertBefore(e,f)},this);
  %body{"style" => "margin-top: 45px"}
    = yield
    = redux_store_hydration_data