config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  resources :members

  resources :meeting_members

  resources :belts

  resources :roles

  resources :schools

  resources :meetings

  get 'test', controller: :meetings, action: :test, as: :test

  resources :meeting_types

  # You can have the root of your site routed with "root"
  root 'home#index'

  get 'home/reports' => 'home#reports', as: :reports
  
  get 'home/poor_attendance' => 'home#poor_attendance', as: :poor_attendance
  get 'home/slacker_report' => 'home#slacker_report', as: :slacker_report
  get 'home/classes_per_student' => 'home#classes_per_student', as: :classes_per_student
  get 'home/people_per_class' => 'home#people_per_class', as: :people_per_class

  get 'attendance/(for/:school)', controller: :meetings, action: :new, as: :attendance

  get 'dashboard/(for/:school)', controller: :home, action: :dashboard, as: :dashboard

  get 'home/attendance', controller: :home, action: :attendance_for_all_time
  get 'home/attendance/:year', controller: :home, action: :attendance_for_year
  get 'home/attendance/:year/:month', controller: :home, action: :attendance_for_month
end

app/models/member.rb
class Member < ApplicationRecord
  belongs_to :belt
  belongs_to :school
  has_many :meeting_members
  has_many :meetings, through: :meeting_members

  # default_scope { where(is_active: true) }

  scope :for_school, ->(school) { where(school_id: school.id) unless school.nil? }
  scope :active, -> { where(is_active: true) }

  def self.members_for_query(query, active = true)
    members = []

    # We prioritize belt names over users
    belts = Belt.where("name ILIKE '%#{query}%'")

    belts.each do |belt|
      members = members + belt.members
      members.delete_if{|mem| mem.is_active != active}
    end

    members += Member.where("first_name ILIKE '%#{query}%' OR last_name ILIKE '%#{query}%'").where(is_active: active)

    members
  end

  def self.members_for_typeahead(school = nil)
    members = school.nil? ? Member.where(is_active: true) : Member.where(school: school, is_active: true)

    members.collect do |member|
      {
        id: member.id,
        value: member.full_name,
        belt: member.belt.name,
        school: member.school ? member.school.name : ''
      }
    end
  end

  def full_name
    name = first_name
    name = name + " " + last_name if not last_name.empty?
    name
  end

  # Priority for oldest
  def age_role_to_str
    if is_teen
      'teen'
    elsif is_kid
      'kid'
    elsif is_quark
      'quark'
    else
      'adult'
    end
  end

  def meetings_for_last_30_days
    meetings = MeetingMember.meetings_for_member(self)

    if meetings.length > 0
      MeetingMember.meetings_for_member(self).met_after(Time.now - 30.days)
    else
      []
    end
  end

  def meetings_for_previous_30_days
    meetings = MeetingMember.meetings_for_member(self)

    if meetings.length > 0
      MeetingMember.meetings_for_member(self).met_between(Time.now - 30.days, Time.now - 60.days)
    else
      []
    end
  end
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
  MEETINGS_TO_SHOW_DEFAULT = 10
  MEMBERS_LIMIT_DEFAULT = 50
  before_action :set_member, only: [:show, :edit, :update, :destroy]

  skip_before_action :verify_authenticity_token

  # GET /members
  # GET /members.json
  def index
    show_inactive = params[:show_inactive] || false
    limit = params[:limit] || MEMBERS_LIMIT_DEFAULT
    query = params[:query] || nil
    members = []

    if not query.nil?
      active = params.fetch(:active, nil)

      if active.nil?
        active = true
      else
        active = active == "true"
      end

      members = Member.members_for_query(query, active)
    else
      if show_inactive && show_inactive == 'true'
        members = Member.order("last_name").for_school(current_school).where(is_active: false).includes(:belt)
      else
        members = Member.active.order("last_name").for_school(current_school).includes(:belt)
      end
    end

    @members = members
    @show_inactive = show_inactive

    respond_to do |format|
      format.html { render :index }
      format.json { render json: @members.to_json(include: :belt) }
    end
  end

  # GET /members/1
  # GET /members/1.json
  def show
    if params.key?(:meetings_to_show)
      session[:meetings_to_show] = params[:meetings_to_show]
    end

    @meetings_to_show = session[:meetings_to_show] || MEETINGS_TO_SHOW_DEFAULT

    respond_to do |format|
      format.html { render :show }
      format.json { render json: @member }
    end
  end

  # GET /members/new
  def new
    @member = Member.new
    @member.is_active = true
  end

  # GET /members/1/edit
  def edit
  end

  # POST /members
  # POST /members.json
  def create
    @member = Member.new(member_params)

    respond_to do |format|
      if @member.save
        format.html { redirect_to @member, notice: 'Member was successfully created.' }
        format.json { render :show, status: :created, location: @member }
      else
        format.html { render :new }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /members/1
  # PATCH/PUT /members/1.json
  def update
    respond_to do |format|
      if @member.update(member_params)
        format.html { redirect_to @member, notice: 'Member was successfully updated.' }
        format.json { render :show, status: :ok, location: @member }
      else
        format.html { render :edit }
        format.json { render json: @member.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /members/1
  # DELETE /members/1.json
  def destroy
    @member.destroy
    respond_to do |format|
      format.html { redirect_to members_url, notice: 'Member was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_member
    @member = Member.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the allowed list through.
  def member_params
    params.require(:member).permit(:first_name, :last_name, :belt_id, :school_id, :comment, :is_active, :is_teacher, :is_quark, :is_kid, :is_teen)
  end
end

app/helpers/members_helper.rb
module MembersHelper
end

app/views/members/_form.html.haml
= form_for @member, :html => { :class => 'form-horizontal' } do |f|
  .form-group
    = f.label :first_name
    = f.text_field :first_name, :class => 'form-control'
  .form-group
    = f.label :last_name
    = f.text_field :last_name, :class => 'form-control'
  .form-group
    = f.label :belt_id
    = f.select(:belt_id, Belt.all.collect{|belt| [belt.name, belt.id]}, {}, {class: "form-control"})
  .form-group
    = f.label :school_id
    = f.select(:school_id, School.all.collect{|belt| [belt.name, belt.id]}, {}, {class: "form-control"})
  .form-group
    = f.label :comment
    = f.text_field :comment, :class => 'form-control'
  .form-group
    .checkbox
      %label
        = f.check_box :is_active, :class => 'check_box'
        Is Active
  .form-group
    .checkbox
      %label
        = f.check_box :is_teacher, :class => 'check_box'
        Is Teacher
  .form-group
    .checkbox
      %label
        = f.check_box :is_quark, :class => 'check_box'
        Is Quark
  .form-group
    .checkbox
      %label
        = f.check_box :is_kid, :class => 'check_box'
        Is Kid
  .form-group
    .checkbox
      %label
        = f.check_box :is_teen, :class => 'check_box'
        Is Teen
  .form-actions
    = f.submit nil, :class => 'btn btn-primary'
    = link_to t('.cancel', :default => t("helpers.links.cancel")), |
      members_path, :class => 'btn'                                |

app/views/members/_member_list.html.haml
- model_class = Member
%table.table.table-striped.tablesorter#members-table
  %thead
    %tr
      %th
        Name
      %th= model_class.human_attribute_name(:belt_id)
      %th= model_class.human_attribute_name(:school_id)
      %th= model_class.human_attribute_name(:comment)
      %th= model_class.human_attribute_name(:is_active)
      %th= model_class.human_attribute_name(:is_teacher)
      %th Age Role
      %th= t '.actions', :default => t("helpers.actions")
  %tbody
    - @members.each do |member|
      %tr
        %td= link_to member.full_name, member_path(member)
        %td= member.belt.name
        %td= member.school ? member.school.name : ''
        %td= member.comment
        %td= member.is_active
        %td= member.is_teacher
        %td= member.age_role_to_str
        %td
          = link_to t('.edit', :default => t("helpers.links.edit")), edit_member_path(member), :class => 'btn btn-default'

:javascript
  $(document).ready(function() {
    $("#members-table").tablesorter();
  });

app/views/members/_member_select.html.haml
-# To bind on select, use $("#find-student .typeahead).on('typeahead:selected', ...
#find-student
  .dataset-selector{:style => "padding-bottom: 3px"}
    .checkbox
      %label
        = check_box_tag "use_all_students", 1, false
        Use All Students
  .find-input
    %input#student-search-input{:type => "text", :class => "typeahead form-control", :placeholder => "Find a Student"}

:javascript
  $(document).ready(function() {
    var useAllStudentsBox = $("#use_all_students");
    var allMembers = [#{Member.members_for_typeahead().map{|mem| mem.to_json}.join(",").html_safe}];
    var members = [#{Member.members_for_typeahead(@_current_school).map{|mem| mem.to_json}.join(",").html_safe}];

    var engine = new Bloodhound({
      datumTokenizer: Bloodhound.tokenizers.obj.whitespace('value', 'belt'),
      queryTokenizer: Bloodhound.tokenizers.whitespace,
      local: members
    });

    // Set up a way to toggle between data sets.
    useAllStudentsBox.change(function() {
      if ($(this).is(":checked")) {
        engine.clear();
        engine.add(allMembers);
        console.log("Member Search: updated to have all members.");
      }
      else {
        engine.clear();
        engine.add(members);
        console.log("Member Search: updated to only have current school's members.");
      }
    });

    $('#find-student .typeahead').typeahead({
      hint: true,
      highlight: true,
      minLength: 2
    }, {
      name: 'members',
      displayKey: 'value',
      source: engine.ttAdapter(),
      templates: {
        suggestion: Handlebars.compile("<p><strong>{{value}}</strong> - {{belt}} (<i>{{school}}</i>)</p>")
      }
    });
  });

app/views/members/edit.html.haml
- model_class = Member
.page-header
  %h1= t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/members/index.html.haml
- model_class = Member
- @show_new = true
.page-header
  %h1= t '.title', :default => model_class.model_name.human.pluralize.titleize

.container
  = link_to "Create New Member", new_member_path, { class: "btn btn-primary" }

.container
  - if @show_inactive
    = link_to "Show Active", members_path
  - else
    = link_to "Show Inactive", members_path(show_inactive: true)

= render 'member_list'

app/views/members/new.html.haml
- model_class = Member
.page-header
  %h1= t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize
= render :partial => 'form'

app/views/members/show.html.haml
- model_class = Member
.page-header
  %h1= t '.title', :default => model_class.model_name.human.titleize + ": " + @member.full_name

.container-fluid
  .row-fluid
    .col-md-6
      %dl.dl-horizontal
        %dt
          %strong
            = model_class.human_attribute_name(:belt_id)
            \:
        %dd= @member.belt.name
        %dt
          %strong
            = model_class.human_attribute_name(:school_id)
            \:
        %dd= @member.school.name
        %dt
          %strong
            = model_class.human_attribute_name(:comment)
            \:
        %dd= (@member.comment && !@member.comment.empty?) ? @member.comment : "None"
        %dt
          %strong
            = model_class.human_attribute_name(:is_active)
            \:
        %dd= @member.is_active
        %dt
          %strong
            = model_class.human_attribute_name(:is_teacher)
            \:
        %dd= @member.is_teacher
        %dt
          %strong
            = model_class.human_attribute_name(:is_quark)
            \:
        %dd= @member.is_quark
        %dt
          %strong
            = model_class.human_attribute_name(:is_kid)
            \:
        %dd= @member.is_kid
        %dt
          %strong
            = model_class.human_attribute_name(:is_teen)
            \:
        %dd= @member.is_teen
    .col-md-6
      .container-fluid
        .row
          .col-md-6
            #classes-last-30-days
          .col-md-6
            #classes-previous-30-days
        .row
          .col-md-12
            #class-types

.container
  %form.form-inline{action: member_path(@member), method: "get", id: "meetings_to_show_form", name: "meetings_to_show_form"}
    .form-group
      %label{for: "meetings_to_show"}
        Number of classes to show:
      %select#meetings_to_show.form-control{name: "meetings_to_show"}
        = options_for_select([10, 50, 100].collect{|num| [num.to_s, num]}, @meetings_to_show)

%h3= "Last #{@meetings_to_show} Classes"
%table.table.table-striped
  %thead
    %tr
      %th= model_class.human_attribute_name(:meeting_type_id)
      %th= model_class.human_attribute_name(:met)
      %th Role
      %th Num Students
      %th= model_class.human_attribute_name(:comment)
  %tbody
    - @member.meetings.order("met DESC").limit(@meetings_to_show).each do |meeting|
      - mm = MeetingMember.where(member_id: @member.id, meeting_id: meeting.id).first
      %tr
        %td= link_to meeting.meeting_type.name, meeting_path(meeting)
        %td= meeting.met.to_s(:long) if meeting.met
        %td= mm.role.name
        %td= meeting.members.count
        %td= meeting.comment

.form-actions
  = link_to t('.back', :default => t("helpers.links.back")), members_path, :class => 'btn btn-default'
  = link_to t('.edit', :default => t("helpers.links.edit")), edit_member_path(@member), :class => 'btn btn-default'
  = link_to t('.destroy', :default => t("helpers.links.destroy")), member_path(@member), :method => 'delete', :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) }, :class => 'btn btn-danger'

:javascript
  $(document).ready(function() {
    $("#meetings_to_show").change(function() {
      this.form.submit();
    });

    var last30 = new Keen.Dataviz()
      .el("#classes-last-30-days")
      .colors(['blue'])
      .height(120)
      .title("Classes Last 30 Days")
      .type('metric')
      .data({'result': #{@member.meetings_for_last_30_days.length}})
      .render();

    var prev30 = new Keen.Dataviz()
      .el("#classes-previous-30-days")
      .colors(['grey'])
      .height(120)
      .title("Classes Prev 30 Days")
      .type('metric')
      .data({'result': #{@member.meetings_for_previous_30_days.length}})
      .render();
  });